import { GoogleGenAI } from "@google/genai";

// Ensure the API key is available in the environment variables
if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const getStylePromptPrefix = (style: string): string => {
    switch (style) {
        case 'Cartoon':
            return `A vibrant, professional product photo of the following item, in a bold and clean cartoon style, on a pure white background:`;
        case 'Watercolor':
            return `A beautiful, artistic product photo of the following item, in a soft and elegant watercolor style, on a pure white background:`;
        case 'Realistic':
        default:
            return `A professional, clean product photo of the following item, on a pure white background:`;
    }
};


/**
 * Generates a product image based on a user's prompt and selected style.
 * @param prompt - The user's description of the product.
 * @param style - The artistic style for the image ('Realistic', 'Cartoon', 'Watercolor').
 * @returns A base64 encoded image URL string.
 */
export const generateProductImage = async (prompt: string, style: string): Promise<string> => {
    try {
        const stylePrefix = getStylePromptPrefix(style);
        const fullPrompt = `${stylePrefix} ${prompt}. The image should be high-resolution and look like it's for an e-commerce website.`;
        
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: fullPrompt,
            config: {
                numberOfImages: 1,
                outputMimeType: 'image/png',
                aspectRatio: '1:1',
            },
        });

        if (!response.generatedImages || response.generatedImages.length === 0) {
            throw new Error("No image was generated by the API.");
        }

        const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
        return `data:image/png;base64,${base64ImageBytes}`;

    } catch (error) {
        console.error("Error generating image:", error);
        throw new Error("Could not generate product image.");
    }
};

/**
 * Generates a short, catchy product title based on a user's prompt.
 * @param prompt - The user's description of the product.
 * @returns A string containing the product title.
 */
export const generateProductTitle = async (prompt: string): Promise<string> => {
    const titlePrompt = `Based on the following product description, create a short, catchy and descriptive product title (5 words maximum). Do not use quotes in the title. Description: "${prompt}"`;
    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: titlePrompt,
        });
        // Fix: Use response.text to get the generated text content.
        const title = response.text.trim().replace(/"/g, ''); // Remove any quotes from the response
        return title;
    } catch (error) {
        console.error("Error generating title:", error);
        throw new Error("Could not generate product title.");
    }
};
