export const generateProduct = async (prompt: string, style: string): Promise<string> => {
    try {
        const stylePrefix = getStylePromptPrefix(style);
        const fullPrompt = `${stylePrefix} ${prompt}. The image should be high-resolution and look like it's for an e-commerce website.`;
        
        const response = await fetch('http://localhost:5275/generateProduct', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ Prompt: prompt, Style: style  }),
        });
        console.log("response", response);
        if (!response.ok) {
            throw new Error(`API error: ${response.status}`);
        }

        const data = await response.json();
        console.log("data", data);
        return data.image;

        // const response = await ai.models.generateImages({
        //     model: 'imagen-4.0-generate-001',
        //     prompt: fullPrompt,
        //     config: {
        //         numberOfImages: 1,
        //         outputMimeType: 'image/png',
        //         aspectRatio: '1:1',
        //     },
        // });

        // if (!response.generatedImages || response.generatedImages.length === 0) {
        //     throw new Error("No image was generated by the API.");
        // }

        // const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
        // return `data:image/png;base64,${base64ImageBytes}`;

    } catch (error) {
        console.error("Error generating image:", error);
        throw new Error("Could not generate product image.");
    }
};

const getStylePromptPrefix = (style: string): string => {
    switch (style) {
        case 'Cartoon':
            return `A vibrant, professional product photo of the following item, in a bold and clean cartoon style, on a pure white background:`;
        case 'Watercolor':
            return `A beautiful, artistic product photo of the following item, in a soft and elegant watercolor style, on a pure white background:`;
        case 'Realistic':
        default:
            return `A professional, clean product photo of the following item, on a pure white background:`;
    }
};